server:
  port: 7991

spring:
   application:
    name: dxt-third-task
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.150.187:1433;DatabaseName=dxtpeter
    username: eshang
    password: dxt_619!@#
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  #实体类所做包
  type-aliases-package: com.dxt
  #mapper.xml所在位置
  mapper-locations: classpath:com.dxt.third.core.dao/*.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.100.228:7001//eureka/
  instance:
    instance-id: dxt-third-task-7991
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: dxt-third-task
  company.name: www.lwt.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#E商接口地址配置
esale:
  charge:
    order:
      send.key: RtLu8Q@5YHUv8birZa1%
      stsout.key: xrRFie1=ls.%f2384#*.9
      send.address: https://beijing.dxteshang.com/interface/Sales_CreateSaleEx.asp
    #E商调拨出库单生成接口
      stsout.address: https://beijing.dxteshang.com/stsout.asp?accesstoken=
    #E商调拨入库单生成接口
      stsin.address: https://beijing.dxteshang.com/stsin.asp?accesstoken=